paths:
  bids_root: "/Volumes/HardDiskYF/ACADEMIA/EEG/ds006761-download"
  output_dir: "/Volumes/HardDiskYF/ACADEMIA/EEG/derivatives_new2"
  report_dir: "/Volumes/HardDiskYF/ACADEMIA/EEG/report_new2"

subjects:
  include: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34]

params:
  task_name: "RPS"
  
  # Epoching (Time relative to trigger in seconds)
  tmin: -0.2
  tmax: 5.0
  
  # Resampling
  origin_fs: 2048
  target_fs: 256
  resample_method: "polyphase" # Validated: scipy.signal.resample_poly
  resample_pad: "mean"         # Validated: Matches MATLAB boundary behavior
  
  # Interpolation
  # "fieldtrip_nearest": Custom IDW (Inverse Distance Weighting) -> Validated Step 3
  # "spline": MNE Standard (Spherical Splines) -> Validated (High Corr, Morphologically good)
  interp_method: "fieldtrip_nearest" 
  neighbor_count: 5            # Number of neighbors for IDW (FieldTrip default-ish)

# --- GUARDRAILS (Not yet validated features) ---
# Features that are implemented but disabled to ensure MATLAB identity.
# Setting these to 'true' will raise an error until validation code is removed.
guardrails:
  allow_highpass: false
  allow_lowpass: false
  allow_notch: false
  allow_rereference: false
  allow_ica: false

# --- CRITICAL: CHANNEL MAPPING (Hardware -> 10-20) ---
# Required for correct topology and interpolation.
# Based on BioSemi 64 Standard Layout (10-20 system).
channel_mapping:
  # Player 1 (Prefix 2-)
  "2-A1": "Fp1"
  "2-A2": "AF7"
  "2-A3": "AF3"
  "2-A4": "F1"
  "2-A5": "F3"
  "2-A6": "F5"
  "2-A7": "F7"
  "2-A8": "FT7"
  "2-A9": "FC5"
  "2-A10": "FC3"
  "2-A11": "FC1"
  "2-A12": "C1"
  "2-A13": "C3"
  "2-A14": "C5"
  "2-A15": "T7"
  "2-A16": "TP7"
  "2-A17": "CP5"
  "2-A18": "CP3"
  "2-A19": "CP1"
  "2-A20": "P1"
  "2-A21": "P3"
  "2-A22": "P5"
  "2-A23": "P7"
  "2-A24": "P9"
  "2-A25": "PO7"
  "2-A26": "PO3"
  "2-A27": "O1"
  "2-A28": "Iz"
  "2-A29": "Oz"
  "2-A30": "POz"
  "2-A31": "Pz"
  "2-A32": "CPz"
  "2-B1": "Fpz"
  "2-B2": "Fp2"
  "2-B3": "AF8"
  "2-B4": "AF4"
  "2-B5": "AFz"
  "2-B6": "Fz"
  "2-B7": "F2"
  "2-B8": "F4"
  "2-B9": "F6"
  "2-B10": "F8"
  "2-B11": "FT8"
  "2-B12": "FC6"
  "2-B13": "FC4"
  "2-B14": "FC2"
  "2-B15": "FCz"
  "2-B16": "Cz"
  "2-B17": "C2"
  "2-B18": "C4"
  "2-B19": "C6"
  "2-B20": "T8"
  "2-B21": "TP8"
  "2-B22": "CP6"
  "2-B23": "CP4"
  "2-B24": "CP2"
  "2-B25": "P2"
  "2-B26": "P4"
  "2-B27": "P6"
  "2-B28": "P8"
  "2-B29": "P10"
  "2-B30": "PO8"
  "2-B31": "PO4"
  "2-B32": "O2"